CREATE DATABASE encuestas;
USE encuestas;

CREATE TABLE resultados
(
	id 				INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    fecha 			DATETIME NOT NULL DEFAULT NOW(),
    ruc 			CHAR(11) NOT NULL,
    razonsocial		VARCHAR(250) NOT NULL,
    nombrecomercial	VARCHAR(100) NOT NULL,
    
    arequipa 		ENUM('S', 'N') NOT NULL DEFAULT 'N',
    ica 			ENUM('S', 'N') NOT NULL DEFAULT 'N',
    junin 			ENUM('S', 'N') NOT NULL DEFAULT 'N',
    lalibertad 		ENUM('S', 'N') NOT NULL DEFAULT 'N',
    lambayeque 		ENUM('S', 'N') NOT NULL DEFAULT 'N',
    piura 			ENUM('S', 'N') NOT NULL DEFAULT 'N',
    sanmartin 		ENUM('S', 'N') NOT NULL DEFAULT 'N',
    tumbes 			ENUM('S', 'N') NOT NULL DEFAULT 'N',
    otrazona		VARCHAR(50) NULL,
    
    arandano		ENUM('S', 'N') NOT NULL DEFAULT 'N',
    palta 			ENUM('S', 'N') NOT NULL DEFAULT 'N',
    esparrago		ENUM('S', 'N') NOT NULL DEFAULT 'N',
    uva				ENUM('S', 'N') NOT NULL DEFAULT 'N',
    mango 			ENUM('S', 'N') NOT NULL DEFAULT 'N',
    otrocultivo		VARCHAR(50) NULL,
    
    s2_reg_dsp		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Regador', 
    s2_reg_num 		SMALLINT NOT NULL,
    s2_osr_dsp    	ENUM('C', 'M', 'A') NOT NULL COMMENT 'Operador de sistemas de riego',
    s2_osr_num		SMALLINT NOT NULL,
    s2_efi_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Evaluador fitosanitario',
    s2_efi_num 		SMALLINT NOT NULL,
    s2_afi_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Aplicador fitosanitario',
    s2_afi_num 		SMALLINT NOT NULL,
    s2_lco_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Líderes de cosecha',
    s2_lco_num		SMALLINT NOT NULL,
    s2_ooc_des		VARCHAR(50) NULL COMMENT 'Otro operario calificado',
    s2_ooc_dsp 		ENUM('C', 'M', 'A') NULL,
    s2_ooc_num		SMALLINT NULL,
    s2_oma_dsp		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Operador de maquinaria agrícola',
    s2_oma_num		SMALLINT NOT NULL,
    s2_ins_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Inspector de calidad de sistemas de riego',
    s2_ins_num		SMALLINT NOT NULL,
    s2_otc_des		VARCHAR(50) NULL COMMENT 'Otro técnico calificado',
    s2_otc_dsp 		ENUM('C', 'M', 'A') NULL,
    s2_otc_num		SMALLINT NULL,
    
    s3_omo_dsp		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Operadores de montacarga',
    s3_omo_num 		SMALLINT NOT NULL,
    s3_osr_dsp		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Operadores de sistemas de riego',
    s3_osr_num		SMALLINT NOT NULL,
    s3_ooc_des 		VARCHAR(50) NULL COMMENT 'Otro operario calificado - sección 3',
    s3_ooc_dsp 		ENUM('C', 'M', 'A') NOT NULL,
    s3_ooc_num		SMALLINT NOT NULL,
    s3_fri_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Frigorista',
    s3_fri_num		SMALLINT NOT NULL,
    s3_cal_dsp		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Calderista',
    s3_cal_num		SMALLINT NOT NULL,
    s3_aux_dsp		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Auxiliar de producción',
    s3_aux_num 		SMALLINT NOT NULL,
    s3_ica_dsp   	ENUM('C', 'M', 'A') NOT NULL COMMENT 'Inspector de calidad',
    s3_ica_num	 	SMALLINT NOT NULL,
    s3_otc_des 		VARCHAR(50) NULL COMMENT 'Otro técnico calificado - sección 3',
    s3_otc_dsp 		ENUM('C', 'M', 'A') NULL,
    s3_otc_num 		SMALLINT NULL,
    
    s4_dig_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Digitador',
    s4_dig_num 		SMALLINT NOT NULL,
    s4_oap_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Operatio de aplicaciones',
    s4_oap_num 		SMALLINT NOT NULL,
    s4_ooc_des 		VARCHAR(50) NULL COMMENT 'Otro operario calificado',
    s4_ooc_dsp 		ENUM('C', 'M', 'A') NULL,
    s4_ooc_num 		SMALLINT NULL,
    s4_aux_dsp 		ENUM('C', 'M', 'A') NOT NULL COMMENT 'Auxiliar administrativo',
    s4_aux_num 		SMALLINT NOT NULL,
    s4_otc_des 		VARCHAR(50) NULL COMMENT 'Otro técnico calificado - sección 4',
    s4_otc_dsp 		ENUM('C', 'M', 'A') NULL,
    s4_otc_num		SMALLINT NULL
    
)ENGINE INNODB;

SELECT * FROM resultados;